apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: strimzi-core
    namespace: argocd
spec:
    project: default
    source:
        chart: strimzi/strimzi-kafka-operator
        repoURL: https://strimzi.io/charts/
        targetRevision: 0.34.0
        helm:
            releaseName: strimzi-core
    destination:
        server: "https://kubernetes.default.svc"
        namespace: kubeseal